import { contextBridge, ipcRenderer } from 'electron';
import type { AssistantRequest, DesktopApi, SaveSettingsRequest } from '../shared/contracts';

const api: DesktopApi = {
  getAppInfo: () => ipcRenderer.invoke('app:info'),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: (input: SaveSettingsRequest) => ipcRenderer.invoke('settings:save', input),
  sendMessage: (input: AssistantRequest) => ipcRenderer.invoke('assistant:send', input),
  onAssistantDelta: (callback) => { const listener = (_event: Electron.IpcRendererEvent, delta: string) => callback(delta); ipcRenderer.on('assistant:delta', listener); return () => ipcRenderer.removeListener('assistant:delta', listener); },
  loadHistory: () => ipcRenderer.invoke('history:load'),
  clearHistory: () => ipcRenderer.invoke('history:clear'),
  listPermissions: () => ipcRenderer.invoke('permissions:list'),
  setPermission: (id,enabled) => ipcRenderer.invoke('permissions:set',id,enabled),
  loadAudit: () => ipcRenderer.invoke('audit:list'),
  clearAudit: () => ipcRenderer.invoke('audit:clear'),
  captureScreen: () => ipcRenderer.invoke('screen:capture'),
  getSystemTelemetry: () => ipcRenderer.invoke('system:telemetry'),
  transcribeAudio: (input) => ipcRenderer.invoke('audio:transcribe', input),
  openRealtimeTranscription: (sdp) => ipcRenderer.invoke('audio:realtime-transcription',sdp),
  synthesizeSpeech: (text) => ipcRenderer.invoke('audio:synthesize', text),
  listElevenLabsVoices: () => ipcRenderer.invoke('elevenlabs:voices'),
  testProvider: (provider) => ipcRenderer.invoke('settings:test-provider', provider),
  getProviderHealth: () => ipcRenderer.invoke('settings:provider-health'),
  getOperationalSnapshot: (force) => ipcRenderer.invoke('operations:snapshot',force),
  reportRendererCapabilities: (report) => ipcRenderer.invoke('operations:renderer',report),
  reportConversationLatency: (report) => ipcRenderer.invoke('operations:latency',report),
  saveVoiceProfile: (name) => ipcRenderer.invoke('voice-profile:save',name),
  activateVoiceProfile: (id) => ipcRenderer.invoke('voice-profile:activate',id),
  deleteVoiceProfile: (id) => ipcRenderer.invoke('voice-profile:delete',id),
  listKnownPeople: () => ipcRenderer.invoke('people:list'),
  saveKnownPerson: (name,descriptor) => ipcRenderer.invoke('people:save',name,descriptor),
  markKnownPersonSeen: (id) => ipcRenderer.invoke('people:seen',id),
  forgetKnownPerson: (id) => ipcRenderer.invoke('people:forget',id),
  enrollSpeaker: (name,vector) => ipcRenderer.invoke('speaker:enroll',name,vector),
  matchSpeaker: (vector,visiblePersonName) => ipcRenderer.invoke('speaker:match',vector,visiblePersonName),
  forgetSpeaker: (id) => ipcRenderer.invoke('speaker:forget',id),
  getPlatformPermissions: () => ipcRenderer.invoke('platform-permissions:get'),
  openPlatformPermission: (id) => ipcRenderer.invoke('platform-permissions:open',id),
  listMemories: () => ipcRenderer.invoke('memory:list'),
  addMemory: (text,kind) => ipcRenderer.invoke('memory:add', text,kind),
  forgetMemory: (id) => ipcRenderer.invoke('memory:forget',id),
  listGoals: () => ipcRenderer.invoke('goals:list'),
  addGoal: (title) => ipcRenderer.invoke('goals:add', title),
  listTodos: () => ipcRenderer.invoke('todos:list'),
  addTodo: (text) => ipcRenderer.invoke('todos:add',text),
  setTodoStatus: (id,status) => ipcRenderer.invoke('todos:status',id,status),
  removeTodo: (id) => ipcRenderer.invoke('todos:remove',id),
  getSchedulerSnapshot: () => ipcRenderer.invoke('scheduler:snapshot'),
  saveAgent: (input) => ipcRenderer.invoke('agents:save',input),
  setAgentEnabled: (id,enabled) => ipcRenderer.invoke('agents:enabled',id,enabled),
  runAgentNow: (id) => ipcRenderer.invoke('agents:run',id),
  removeAgent: (id) => ipcRenderer.invoke('agents:remove',id),
  addMonitor: (input) => ipcRenderer.invoke('monitors:add',input),
  stopMonitor: (id) => ipcRenderer.invoke('monitors:stop',id),
  onBackgroundEvent: (callback) => { const listener=(_event:Electron.IpcRendererEvent,value:Parameters<typeof callback>[0])=>callback(value);ipcRenderer.on('background:event',listener);return()=>ipcRenderer.removeListener('background:event',listener); },
  onCameraCaptureRequest: (callback) => { const listener=(_event:Electron.IpcRendererEvent,value:Parameters<typeof callback>[0])=>callback(value);ipcRenderer.on('background:camera-request',listener);return()=>ipcRenderer.removeListener('background:camera-request',listener); },
  submitCameraCapture: (id,capture,error) => ipcRenderer.send('background:camera-response',id,capture,error),
  listConnectors: () => ipcRenderer.invoke('connectors:list'),
  saveConnector: (input) => ipcRenderer.invoke('connectors:save',input),
  connectConnector: (id) => ipcRenderer.invoke('connectors:connect',id),
  disconnectConnector: (id) => ipcRenderer.invoke('connectors:disconnect',id),
  testConnector: (id) => ipcRenderer.invoke('connectors:test',id),
  getHomebridgeSnapshot: () => ipcRenderer.invoke('homebridge:snapshot'),
  controlHomebridge: (input) => ipcRenderer.invoke('homebridge:control',input),
  connectRing: (email,password,twoFactorCode) => ipcRenderer.invoke('ring:connect',email,password,twoFactorCode),
  listRingCameras: () => ipcRenderer.invoke('ring:cameras'),
  openRingLiveView: (cameraId,offerSdp) => ipcRenderer.invoke('ring:liveview-open',cameraId,offerSdp),
  sendRingIceCandidate: (liveSessionId,candidate,sdpMLineIndex) => ipcRenderer.invoke('ring:liveview-ice',liveSessionId,candidate,sdpMLineIndex),
  closeRingLiveView: (liveSessionId) => ipcRenderer.invoke('ring:liveview-close',liveSessionId),
  onRingLiveViewEvent: (callback) => { const listener=(_event:Electron.IpcRendererEvent,value:Parameters<typeof callback>[0])=>callback(value);ipcRenderer.on('ring:liveview-event',listener);return()=>ipcRenderer.removeListener('ring:liveview-event',listener); },
  listMediaArtifacts: () => ipcRenderer.invoke('media:list'),
  showCursorGuide: (x,y,label,durationMs) => ipcRenderer.invoke('cursor-guide:show',x,y,label,durationMs),
  openGodsEyeView: () => ipcRenderer.invoke('gods-eye:open'),
  setGodsEyeViewBounds: (bounds) => ipcRenderer.invoke('gods-eye:set-bounds',bounds),
  closeGodsEyeView: () => ipcRenderer.invoke('gods-eye:close'),
  getRuntimeSnapshot: () => ipcRenderer.invoke('runtime:snapshot'),
  addCommitment: (title,dueAt) => ipcRenderer.invoke('commitments:add',title,dueAt),
  resolveCommitment: (id,status) => ipcRenderer.invoke('commitments:resolve',id,status),
  cancelRuntimeTask: (id) => ipcRenderer.invoke('runtime:cancel-task',id),
  decideApproval: (id,decision) => ipcRenderer.invoke('approval:decide',id,decision),
  getDesktopGraph: () => ipcRenderer.invoke('desktop-graph:get'),
  refreshDesktopGraph: () => ipcRenderer.invoke('desktop-graph:refresh'),
  createBackup: () => ipcRenderer.invoke('backup:create'),
  createPortableBackup: (passphrase) => ipcRenderer.invoke('backup:create-portable',passphrase),
  chooseBackupFile: () => ipcRenderer.invoke('backup:choose-file'),
  checkForUpdate: () => ipcRenderer.invoke('updates:check'),
  downloadUpdate: () => ipcRenderer.invoke('updates:download'),
  openUpdateInstaller: (filePath) => ipcRenderer.invoke('updates:open-installer',filePath),
  exportAllData: () => ipcRenderer.invoke('data:export'),
  eraseAllData: (confirmation) => ipcRenderer.invoke('data:erase',confirmation),
  verifyOwnerOverride: (phrase) => ipcRenderer.invoke('identity:verify-owner-override',phrase),
  listSelfCorrections: () => ipcRenderer.invoke('self-corrections:list'),
  recordSelfCorrection: (pattern,mistake,fix) => ipcRenderer.invoke('self-corrections:record',pattern,mistake,fix),
  forgetSelfCorrection: (id) => ipcRenderer.invoke('self-corrections:forget',id),
  lastSettingsSnapshot: () => ipcRenderer.invoke('settings:last-snapshot'),
  revertLastSettingsChange: () => ipcRenderer.invoke('settings:revert'),
  restorePortableBackup: (sourcePath,passphrase) => ipcRenderer.invoke('backup:restore-portable',sourcePath,passphrase),
  getSyncStatus: () => ipcRenderer.invoke('sync:status'),
  syncNow: () => ipcRenderer.invoke('sync:now'),
  reportDeviceActivity: () => ipcRenderer.invoke('device:activity'),
  reportRendererCrash: (message,stack,componentStack) => ipcRenderer.invoke('renderer:crash',message,stack,componentStack),
};

contextBridge.exposeInMainWorld('axiom', api);
