const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');

(async()=>{
  const port=process.env.AXIOM_QA_PORT||'9444',target=path.resolve(__dirname,'../tmp/tracking-qa/synthetic-body.png'),dataUrl=`data:image/png;base64,${fs.readFileSync(target).toString('base64')}`;
  const browser=await chromium.connectOverCDP(`http://127.0.0.1:${port}`);const page=browser.contexts().flatMap(context=>context.pages())[0];
  await page.addInitScript((source)=>{const native=navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);Object.defineProperty(navigator.mediaDevices,'getUserMedia',{configurable:true,value:async(constraints)=>{if(!constraints||!constraints.video)return native(constraints);const canvas=document.createElement('canvas');canvas.width=640;canvas.height=480;const context=canvas.getContext('2d'),image=new Image();image.src=source;await image.decode();const started=performance.now();const paint=()=>{const elapsed=(performance.now()-started)/1000;context.fillStyle='#aaa';context.fillRect(0,0,640,480);const height=350,width=height*image.width/image.height,x=(640-width)/2+Math.sin(elapsed*.72)*125,y=65;context.drawImage(image,x,y,width,height);requestAnimationFrame(paint);};paint();return canvas.captureStream(30);}});},dataUrl);
  await page.reload({waitUntil:'domcontentloaded'});await page.waitForSelector('.modded-avatar',{timeout:30000});await page.waitForFunction(()=>document.querySelector('.modded-avatar')?.getAttribute('data-tracking-source')==='body',{timeout:30000});
  const samples=[];for(let index=0;index<32;index+=1){samples.push(await page.evaluate(()=>{const avatar=document.querySelector('.modded-avatar'),style=getComputedStyle(avatar);return{source:avatar?.getAttribute('data-tracking-source'),confidence:Number(avatar?.getAttribute('data-tracking-confidence')),x:parseFloat(style.getPropertyValue('--head-x')),yaw:parseFloat(style.getPropertyValue('--head-yaw'))};}));await page.waitForTimeout(180);}const range=(values)=>Math.max(...values)-Math.min(...values),xs=samples.map(sample=>sample.x),yaws=samples.map(sample=>sample.yaw),confidence=samples.map(sample=>sample.confidence).sort((a,b)=>a-b);
  const result={bodyLocks:samples.filter(sample=>sample.source==='body').length,medianConfidence:confidence[Math.floor(samples.length/2)],headTravelPx:Math.round(range(xs)),yawTravelDeg:Number(range(yaws).toFixed(1))};result.passed=result.bodyLocks>=28&&result.medianConfidence>.35&&result.headTravelPx>=30&&result.yawTravelDeg>=3;console.log(JSON.stringify(result,null,2));await browser.close();if(!result.passed)process.exitCode=1;
})().catch(error=>{console.error(error.stack||error);process.exit(1)});
