import { useEffect, useState } from 'react';
import type { ConnectorId, ConnectorSetup, ConnectorStatus } from '../shared/contracts';

type Draft={account:string;endpoint:string;clientId:string;clientSecret:string;accessToken:string};
const ids:ConnectorId[]=['homebridge','ring','google','shopify','meta','dropbox'];
const blank=():Record<ConnectorId,Draft>=>({
  homebridge:{account:'',endpoint:'http://homebridge.local:8581',clientId:'',clientSecret:'',accessToken:''},ring:{account:'',endpoint:'',clientId:'',clientSecret:'',accessToken:''},google:{account:'',endpoint:'',clientId:'',clientSecret:'',accessToken:''},shopify:{account:'',endpoint:'',clientId:'',clientSecret:'',accessToken:''},meta:{account:'',endpoint:'graph.facebook.com/v24.0',clientId:'',clientSecret:'',accessToken:''},dropbox:{account:'',endpoint:'',clientId:'',clientSecret:'',accessToken:''},
});

export function ConnectorMatrix(){
  const [items,setItems]=useState<ConnectorStatus[]>([]),[drafts,setDrafts]=useState<Record<ConnectorId,Draft>>(blank),[busy,setBusy]=useState(''),[message,setMessage]=useState('');
  // Ring is the one connector needing a follow-up step — a 2FA code is
  // never persisted through Draft/ConnectorSetup like the other fields, it
  // only ever travels as a one-time IPC argument.
  const [ringTwoFactorPending,setRingTwoFactorPending]=useState(false),[ringTwoFactorCode,setRingTwoFactorCode]=useState(''),[ringTwoFactorPrompt,setRingTwoFactorPrompt]=useState('');
  const adopt=(next:ConnectorStatus[])=>{setItems(next);setDrafts((current)=>{const copy={...current};for(const item of next)copy[item.id]={...copy[item.id],account:item.account,endpoint:item.endpoint||copy[item.id].endpoint};return copy;});};
  useEffect(()=>{void window.axiom.listConnectors().then(adopt).catch((reason)=>setMessage(String(reason)));},[]);
  const update=(id:ConnectorId,field:keyof Draft,value:string)=>setDrafts((current)=>({...current,[id]:{...current[id],[field]:value}}));
  const save=async(id:ConnectorId)=>{const draft=drafts[id],input:ConnectorSetup={id,account:draft.account,endpoint:draft.endpoint,clientId:draft.clientId||undefined,clientSecret:draft.clientSecret||undefined,accessToken:draft.accessToken||undefined};const next=await window.axiom.saveConnector(input);adopt(next);setDrafts((current)=>({...current,[id]:{...current[id],clientSecret:'',accessToken:''}}));return next;};
  const act=async(id:ConnectorId,verb:'save'|'connect'|'test'|'disconnect')=>{if(busy)return;setBusy(`${id}-${verb}`);setMessage('');try{
    if(id==='ring'&&verb==='connect'){
      const draft=drafts.ring,result=await window.axiom.connectRing(draft.account,draft.clientSecret,ringTwoFactorPending?ringTwoFactorCode:undefined);
      if('twoFactorRequired' in result){setRingTwoFactorPending(true);setRingTwoFactorPrompt(result.prompt);setMessage(result.prompt);}
      else{setRingTwoFactorPending(false);setRingTwoFactorCode('');setRingTwoFactorPrompt('');adopt(result.status);setDrafts((current)=>({...current,ring:{...current.ring,clientSecret:''}}));setMessage('RING authorization completed.');}
    }else if(verb==='save'){await save(id);setMessage(`${id.toUpperCase()} settings stored in operating-system encryption.`);}
    else if(verb==='connect'){await save(id);adopt(await window.axiom.connectConnector(id));setMessage(`${id.toUpperCase()} authorization completed.`);}
    else if(verb==='test'){await save(id);const result=await window.axiom.testConnector(id);adopt(await window.axiom.listConnectors());setMessage(`${result.label} verified successfully.`);}
    else{adopt(await window.axiom.disconnectConnector(id));if(id==='ring'){setRingTwoFactorPending(false);setRingTwoFactorCode('');setRingTwoFactorPrompt('');}setMessage(`${id.toUpperCase()} credential disconnected.`);}
  }catch(reason){setMessage(reason instanceof Error?reason.message:String(reason));adopt(await window.axiom.listConnectors().catch(()=>items));}finally{setBusy('');}};
  return <div className="connector-matrix"><div className="connector-intro"><div><span>SECURE SERVICE FABRIC</span><b>DIRECT APPLICATION CONNECTIONS</b><p>API access is faster and more reliable than clicking through web pages. Tokens stay encrypted on this device and security-critical actions still enter Axiom’s approval kernel.</p></div><i/></div>{message&&<div className="connector-message">{message}<button onClick={()=>setMessage('')}>×</button></div>}<div className="connector-grid">{ids.map((id)=>{const item=items.find((candidate)=>candidate.id===id),draft=drafts[id];return <section key={id} className={`connector-card ${item?.connected?'connected':item?.configured?'configured':''}`}><header><i/><div><b>{item?.label||id.toUpperCase()}</b><span>{item?.connected?'LIVE + VERIFIED':item?.configured?'CONFIGURED':'NOT CONNECTED'}</span></div><em>{item?.lastCheckedAt?new Date(item.lastCheckedAt).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'—'}</em></header><p>{item?.setupHint}</p>
      {id==='google'?<><label>Desktop OAuth client ID<input value={draft.clientId} onChange={(event)=>update(id,'clientId',event.target.value)} placeholder="…apps.googleusercontent.com"/></label><label>Client secret <small>optional for public desktop clients</small><input type="password" value={draft.clientSecret} onChange={(event)=>update(id,'clientSecret',event.target.value)} placeholder="Stored only if entered"/></label></>:id==='homebridge'?<><label>Homebridge UI URL<input value={draft.endpoint} onChange={(event)=>update(id,'endpoint',event.target.value)} placeholder="http://homebridge.local:8581"/></label><label>Username<input value={draft.account} onChange={(event)=>update(id,'account',event.target.value)} placeholder="admin"/></label><label>Password<input type="password" value={draft.clientSecret} onChange={(event)=>update(id,'clientSecret',event.target.value)} placeholder={item?.configured?'Encrypted password saved — enter to replace':'Homebridge UI sign-in password'}/></label></>:id==='ring'?<><label>Ring account email<input value={draft.account} onChange={(event)=>update(id,'account',event.target.value)} placeholder="you@example.com" disabled={ringTwoFactorPending}/></label><label>Password<input type="password" value={draft.clientSecret} onChange={(event)=>update(id,'clientSecret',event.target.value)} placeholder={item?.configured?'Encrypted password saved — enter to replace':'Ring account password'} disabled={ringTwoFactorPending}/></label>{ringTwoFactorPending&&<label>Verification code<small>{ringTwoFactorPrompt}</small><input value={ringTwoFactorCode} onChange={(event)=>setRingTwoFactorCode(event.target.value)} placeholder="123456"/></label>}</>:<><label>{id==='shopify'?'Store domain':id==='meta'?'Ad account ID':'Account label'}<input value={id==='shopify'?draft.endpoint:draft.account} onChange={(event)=>update(id,id==='shopify'?'endpoint':'account',event.target.value)} placeholder={id==='shopify'?'your-store.myshopify.com':id==='meta'?'act_123456789':'My Dropbox'}/></label>{id==='meta'&&<label>Graph endpoint<input value={draft.endpoint} onChange={(event)=>update(id,'endpoint',event.target.value)} placeholder="graph.facebook.com/v24.0"/></label>}<label>Scoped access token<input type="password" value={draft.accessToken} onChange={(event)=>update(id,'accessToken',event.target.value)} placeholder={item?.connected?'Encrypted token saved — enter to replace':'Paste scoped token'}/></label></>}
      <div className="connector-actions">{id!=='ring'&&<button onClick={()=>void act(id,'save')} disabled={Boolean(busy)}>SAVE</button>}{(id==='google'||id==='ring')&&<button className="primary" onClick={()=>void act(id,'connect')} disabled={Boolean(busy)||(id==='ring'&&(!draft.account||!draft.clientSecret))}>{id==='ring'&&ringTwoFactorPending?'SUBMIT CODE':'CONNECT'}</button>}<button onClick={()=>void act(id,'test')} disabled={Boolean(busy)||!item?.configured}>TEST</button>{item?.connected&&<button className="danger" onClick={()=>void act(id,'disconnect')} disabled={Boolean(busy)}>DISCONNECT</button>}</div>{item?.lastError&&<small className="connector-error">{item.lastError}</small>}{Boolean(item?.scopes.length)&&<small className="connector-scopes">{item!.scopes.join(' · ')}</small>}</section>;})}</div></div>;
}
