import { FormEvent, useEffect, useMemo, useState } from 'react';
import type { MediaArtifact, ScheduleKind, SchedulerSnapshot, TodoItem } from '../shared/contracts';

const scheduleLabel=(schedule:SchedulerSnapshot['agents'][number]['schedule'])=>schedule.kind==='manual'?'MANUAL':schedule.kind==='daily'?`DAILY / ${schedule.dailyTime||'09:00'}`:`EVERY ${schedule.intervalMinutes||60} MIN`;

export function MissionControlPanel(){
  const [scheduler,setScheduler]=useState<SchedulerSnapshot|null>(null);
  const [todos,setTodos]=useState<TodoItem[]>([]);
  const [media,setMedia]=useState<MediaArtifact[]>([]);
  const [todoDraft,setTodoDraft]=useState('');
  const [agentName,setAgentName]=useState('');
  const [agentRole,setAgentRole]=useState('Research operator');
  const [agentInstructions,setAgentInstructions]=useState('');
  const [scheduleKind,setScheduleKind]=useState<ScheduleKind>('manual');
  const [scheduleValue,setScheduleValue]=useState('60');
  const [monitorTitle,setMonitorTitle]=useState('');
  const [monitorInstruction,setMonitorInstruction]=useState('');
  const [monitorSource,setMonitorSource]=useState<'screen'|'camera'>('screen');
  const [monitorMinutes,setMonitorMinutes]=useState('30');
  const [status,setStatus]=useState('');
  const [busy,setBusy]=useState('');
  const refresh=async()=>{const [nextScheduler,nextTodos,nextMedia]=await Promise.all([window.axiom.getSchedulerSnapshot(),window.axiom.listTodos(),window.axiom.listMediaArtifacts()]);setScheduler(nextScheduler);setTodos(nextTodos);setMedia(nextMedia);};
  useEffect(()=>{void refresh().catch((reason)=>setStatus(String(reason)));const timer=window.setInterval(()=>void refresh().catch(()=>{}),3500);return()=>window.clearInterval(timer);},[]);
  const nextWake=useMemo(()=>scheduler?.nextWakeAt?new Date(scheduler.nextWakeAt).toLocaleString():'AWAITING SCHEDULE',[scheduler?.nextWakeAt]);
  const submitTodo=async(event:FormEvent)=>{event.preventDefault();if(!todoDraft.trim())return;await window.axiom.addTodo(todoDraft.trim());setTodoDraft('');await refresh();};
  const submitAgent=async(event:FormEvent)=>{event.preventDefault();if(!agentName.trim()||!agentInstructions.trim())return;setBusy('agent');try{const schedule=scheduleKind==='manual'?{kind:'manual' as const}:scheduleKind==='daily'?{kind:'daily' as const,dailyTime:scheduleValue||'09:00'}:{kind:'interval' as const,intervalMinutes:Math.max(1,Number(scheduleValue)||60)};await window.axiom.saveAgent({name:agentName.trim(),role:agentRole.trim()||'Specialist',instructions:agentInstructions.trim(),schedule});setAgentName('');setAgentInstructions('');setStatus('Specialist agent saved to the persistent scheduler.');await refresh();}catch(reason){setStatus(reason instanceof Error?reason.message:String(reason));}finally{setBusy('');}};
  const submitMonitor=async(event:FormEvent)=>{event.preventDefault();if(!monitorTitle.trim()||!monitorInstruction.trim())return;setBusy('monitor');try{await window.axiom.addMonitor({title:monitorTitle.trim(),instruction:monitorInstruction.trim(),source:monitorSource,intervalSeconds:20,durationMinutes:Math.max(1,Number(monitorMinutes)||30)});setMonitorTitle('');setMonitorInstruction('');setStatus('Visual monitor armed. Axiom will notify you only when its trigger is observed.');await refresh();}catch(reason){setStatus(reason instanceof Error?reason.message:String(reason));}finally{setBusy('');}};
  const act=async(label:string,operation:()=>Promise<unknown>)=>{if(busy)return;setBusy(label);try{await operation();setStatus('Operation verified.');await refresh();}catch(reason){setStatus(reason instanceof Error?reason.message:String(reason));}finally{setBusy('');}};

  return <div className="mission-control">
    <div className="mission-status"><article><span>SCHEDULER</span><b>{scheduler?.running?'ONLINE':'OFFLINE'}</b><small>NEXT WAKE / {nextWake}</small></article><article><span>SPECIALISTS</span><b>{String(scheduler?.agents.filter((item)=>item.enabled).length??0).padStart(2,'0')}</b><small>{scheduler?.agentRuns.filter((item)=>item.status==='active').length??0} ACTIVE RUNS</small></article><article><span>VISUAL WATCH</span><b>{String(scheduler?.monitors.filter((item)=>item.status==='active').length??0).padStart(2,'0')}</b><small>SCREEN + CAMERA</small></article><article><span>MISSION QUEUE</span><b>{String(todos.filter((item)=>item.status==='open').length).padStart(2,'0')}</b><small>ENCRYPTED + SYNCABLE</small></article></div>
    {status&&<div className="mission-notice">{status}<button onClick={()=>setStatus('')}>×</button></div>}
    <div className="mission-grid">
      <section className="mission-card todo-console"><header><div><span>MQ–01</span><b>TO-DO MATRIX</b></div><em>{todos.filter((item)=>item.status==='open').length} OPEN</em></header><form onSubmit={submitTodo}><input value={todoDraft} onChange={(event)=>setTodoDraft(event.target.value)} placeholder="Add a concrete next action…"/><button>ADD</button></form><div className="mission-list">{todos.length?todos.slice().reverse().slice(0,18).map((item)=><article key={item.id} className={item.status}><button className="check" onClick={()=>void act(`todo-${item.id}`,()=>window.axiom.setTodoStatus(item.id,item.status==='open'?'completed':'open'))}>{item.status==='completed'?'✓':'○'}</button><p><b>{item.text}</b><span>{new Date(item.updatedAt).toLocaleString()}</span></p><button className="remove" onClick={()=>void act(`remove-${item.id}`,()=>window.axiom.removeTodo(item.id))}>×</button></article>):<div className="mission-empty">NO QUEUED ACTIONS</div>}</div></section>
      <section className="mission-card agent-console"><header><div><span>AG–02</span><b>SPECIALIST AGENTS</b></div><em>AUTONOMOUS / GUARDED</em></header><form className="agent-form" onSubmit={submitAgent}><div><input value={agentName} onChange={(event)=>setAgentName(event.target.value)} placeholder="Agent name"/><input value={agentRole} onChange={(event)=>setAgentRole(event.target.value)} placeholder="Specialty"/></div><textarea value={agentInstructions} onChange={(event)=>setAgentInstructions(event.target.value)} placeholder="Mission instructions, expected result, and verification criteria…"/><div><select value={scheduleKind} onChange={(event)=>{const next=event.target.value as ScheduleKind;setScheduleKind(next);setScheduleValue(next==='daily'?'09:00':'60');}}><option value="manual">Manual launch</option><option value="interval">Repeating interval</option><option value="daily">Daily</option></select>{scheduleKind!=='manual'&&<input type={scheduleKind==='daily'?'time':'number'} min="1" value={scheduleValue} onChange={(event)=>setScheduleValue(event.target.value)}/>}<button disabled={busy==='agent'}>{busy==='agent'?'SAVING…':'COMMISSION'}</button></div></form><div className="mission-list agents">{scheduler?.agents.length?scheduler.agents.map((agent)=><article key={agent.id} className={agent.enabled?'active':'paused'}><i/><p><b>{agent.name} / {agent.role}</b><span>{scheduleLabel(agent.schedule)} · {agent.runCount} RUNS{agent.lastStatus?` · ${agent.lastStatus.toUpperCase()}`:''}</span><small>{agent.lastResult||agent.instructions}</small></p><div><button onClick={()=>void act(`run-${agent.id}`,()=>window.axiom.runAgentNow(agent.id))}>RUN</button><button onClick={()=>void act(`state-${agent.id}`,()=>window.axiom.setAgentEnabled(agent.id,!agent.enabled))}>{agent.enabled?'PAUSE':'ARM'}</button><button className="remove" onClick={()=>void act(`remove-${agent.id}`,()=>window.axiom.removeAgent(agent.id))}>×</button></div></article>):<div className="mission-empty">NO SPECIALIST AGENTS COMMISSIONED</div>}</div></section>
      <section className="mission-card monitor-console"><header><div><span>VS–03</span><b>VISUAL MONITORS</b></div><em>LOCAL SENSOR / CLOUD REASONING</em></header><form className="agent-form" onSubmit={submitMonitor}><div><input value={monitorTitle} onChange={(event)=>setMonitorTitle(event.target.value)} placeholder="Monitor name"/><select value={monitorSource} onChange={(event)=>setMonitorSource(event.target.value as 'screen'|'camera')}><option value="screen">Display</option><option value="camera">Camera</option></select></div><textarea value={monitorInstruction} onChange={(event)=>setMonitorInstruction(event.target.value)} placeholder="Notify me when… (be precise about the visible trigger)"/><div><label>RUN FOR <input type="number" min="1" max="1440" value={monitorMinutes} onChange={(event)=>setMonitorMinutes(event.target.value)}/> MIN</label><button disabled={busy==='monitor'}>{busy==='monitor'?'ARMING…':'ARM MONITOR'}</button></div></form><div className="mission-list monitors">{scheduler?.monitors.length?scheduler.monitors.slice(0,12).map((monitor)=><article key={monitor.id} className={monitor.status}><i/><p><b>{monitor.title} / {monitor.source.toUpperCase()}</b><span>{monitor.status.toUpperCase()} · NEXT {new Date(monitor.nextRunAt).toLocaleTimeString()}</span><small>{monitor.lastObservation||monitor.instruction}</small></p>{monitor.status==='active'&&<button onClick={()=>void act(`stop-${monitor.id}`,()=>window.axiom.stopMonitor(monitor.id))}>STOP</button>}</article>):<div className="mission-empty">NO ACTIVE VISUAL MONITORS</div>}</div></section>
      <section className="mission-card event-console"><header><div><span>EV–04</span><b>BACKGROUND EVENT TAPE</b></div><em>{scheduler?.events.length??0} RECORDS</em></header><div className="mission-list events">{scheduler?.events.length?scheduler.events.slice(0,16).map((event)=><article key={event.id}><i/><p><b>{event.title}</b><span>{event.kind.toUpperCase()} · {new Date(event.createdAt).toLocaleString()}</span><small>{event.text}</small></p></article>):<div className="mission-empty">BACKGROUND ENGINE IS STANDING BY</div>}</div>{media.length>0&&<div className="artifact-strip"><header>GENERATED MEDIA</header>{media.slice(0,8).map((item)=><article key={item.id} className={item.status}><b>{item.kind.toUpperCase()} / {item.model}</b><span>{item.status.toUpperCase()} · ${item.estimatedCostUsd.toFixed(2)} EST.</span><small>{item.path||item.error||item.prompt}</small></article>)}</div>}</section>
    </div>
  </div>;
}
